In [14]:
import numpy as np
grid = [[5, 3, 0, 0, 7, 0, 0, 0, 0],
        [6, 0, 0, 1, 9, 5, 0, 0, 0],
        [0, 9, 8, 0, 0, 0, 0, 6, 0],
        [8, 0, 0, 0, 6, 0, 0, 0, 3],
        [4, 0, 0, 8, 0, 3, 0, 0, 1],
        [7, 0, 0, 0, 2, 0, 0, 0, 6],
        [0, 6, 0, 0, 0, 0, 2, 8, 0],
        [0, 0, 0, 4, 1, 9, 0, 0, 5],
        [0, 0, 0, 0, 8, 0, 0, 7, 9]]


In [15]:
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [ ]:
def possible(y, x, n) :
    global grid
    for i in range(0,9) :         
        if grid[y][i] == n :    #Look at the entire row to check valid input
            return False
    for i in range(0,9) :
        if grid[i][x] == n :    #Look at the entire column to check valid input
            return False

    x0 = (x//3)*3    #u and v used to check the square n will be placed in
    y0 = (y//3)*3
    
    for i in range(0,3) :
        for j in range(0,3) :     #nested for-loop to check square
            if grid[y0 + i][x0 + j] == n :
                return False
    return True     #if valid placement return true

In [ ]:
possible(4,4,3)


In [ ]:
possible(4,4,5)

In [ ]:
def solve() :   
    global grid
    for y in range(9) :
        for x in range(9) :
            if grid[y][x] == 0 :
                for n in range(1,10) :
                    if possible(y,x,n) :
                        grid[y][x] = n
                        solve()
                        grid[y][x] = 0 
                return
    print(np.matrix(grid))
    input("MORE?")

In [ ]:
solve()